### ISSUE TITLE
Define "EdgeOS" 

### ISSUE THREAD

**Issue by brianredbeard** [devoslab/iotgw_cli#1]
This was discovered while searching for more [EdgeOS][edgeos]™ related resources.  Specifically, this introduced confusion around the existing [EdgeOS CLI][edgeos-cli] interface.

It would be helpful to clarify the relationship between this project and EdgeOS™ as supplied by Ubiquiti networks.

[edgeos]: https://dl.ubnt.com/guides/edgemax/EdgeOS_UG.pdf
[edgeos-cli]: https://networkjutsu.com/edgeos-cli-introduction/

**Comment by DevNaga** [comment]
Thank you for the link on the Ubiquiti CLI. I never knew that there was one with similar name.

First of all, i had no idea about the Ubiquiti project till you filed this issue. This has obviously in no relation with what Ubiquity is doing. So, i'd be happy to change the name to just `CLI` or something.

To define,

"edge-cli" is a command line interface, that has similar functions of a Linux based shell (such as `bash` or `ash` but restricted in programmability) , but doing more than just that. This is meant to be a part in-system CLI and part remote CLI (in communication with the servers in the internet).

**Comment by DevNaga** [comment]
Anyways, i have just changed the name to "iotgw-cli". I'd be changing the other names as well for the rest of my projects. Thanks for your comment !
